require 'open-uri'
require 'nokogiri'
require 'colorize'

require_relative './libri/version'
require_relative './libri/cli'
require_relative './libri/awards.rb'
require_relative './libri/books.rb'
require_relative './libri/book.rb'
require_relative './libri/quote.rb'
require_relative './libri/scraper.rb'